[package]
name = "finalfrontier-python"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[lib]
name = "finalfrontier"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.4"
features = ["extension-module"]

[dependencies]
failure = "0.1"
finalfrontier = { version = "0.1", path = "../finalfrontier/finalfrontier" }
