[package]
name = "finalfrontier-python"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[lib]
name = "finalfrontier"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.5"
features = ["extension-module"]

[dependencies]
failure = "0.1"
finalfrontier = "0.2"
ndarray = "0.11"
